/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
import Modelado_de_procesos.*;
import Estructuras_de_Datos.*;
import main.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.concurrent.atomic.AtomicInteger;

/**
 *
 * @author pjroj
 */
public class Ventana2 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana2
     */
    public Ventana2() {
        initComponents();
        
        //Reloj de sistema en segundos
        Timer timer = new Timer(1000, e -> {
            long ahora = System.currentTimeMillis();
            long segundos = (ahora - CPU.getReloj_global())/1000 ; //entre 1000 para que sea en segundos
            jLabelRelojGlobal.setText(segundos + " seg");
        });
        timer.start();
        
        //Menu para la creacion de procesos (Barra del menu)
        jMenuItemCrearProceso.addActionListener(e -> {
            CrearProceso ventana = new CrearProceso();
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            ventana.setVisible(true);
        });
        
        //Valor de un ciclo en ms, tiene limites entre 500ms y 1000ms
        jSliderCiclo.addChangeListener(e -> {
            int valor = jSliderCiclo.getValue();
            jLabelCiclo.setText(valor + " ms");
        });
        jButtonCambiarCiclo.addActionListener(e -> {
            int valor = jSliderCiclo.getValue();
            CPU.setCiclo_reloj(valor);//en ms
            //System.out.println(CPU.getCiclo_reloj());
        });
        
        CPU.setColaListos(CPU.getColaNuevos());
        ColaListos();
        //Ejecutado();
        
        
        
//        Timer timer = new Timer(4000, e -> {
//            // Código a ejecutar después de 2 segundos
//            Nodo ejecutando = CPU.g
//            CPU.setListo(CPU.getInicial());
//            ColaListos();
//
//            // Aquí puedes actualizar componentes Swing
//            
//        });
//
//        timer.setRepeats(false); // Ejecutar solo una vez
//        timer.start(); // Iniciar el timer
        
    }
    
    private void ColaListos(){
        Nodo pListo = CPU.getColaListos().getHead();
        //configuraciones del panel de fondo del scrollball
        JPanel panelScrollbar =  new JPanel ();
        panelScrollbar.setBackground(Color.decode("#FFFFFF"));
        if(!CPU.getColaListos().isEmpty()){
            while (pListo != null){
                JPanel p =  new JPanel (new GridLayout(0, 1));
                //configuraciones de diseño del proceso
                p.setBackground(Color.decode("#CCCCCC"));
                p.setSize(300,600);
                p.setBorder(BorderFactory.createEmptyBorder(15, 15, 15, 15));
                //ID del proceso
                JLabel id = new JLabel(Integer.toString(pListo.getProceso().getProcesoID()));
                p.add(id,BorderLayout.CENTER);
                //Nombre del proceso
                JLabel proceso = new JLabel(pListo.getProceso().getProcesoNombre());
                p.add(proceso, BorderLayout.CENTER);

                //se agrega al scrollbar
                panelScrollbar.add(p);

                pListo = pListo.getNext();
            } 
            jScrollPaneListo.setViewportView(panelScrollbar);
        }
        
    }
    
    private void Ejecutado(){
        PCB pEjecutado = CPU.getProcesoEnEjecucion();
        //configuraciones para el proceso que se esta ejecutando
        idProceso.setText(Integer.toString(pEjecutado.getProcesoID()));
        nombreProceso.setText(pEjecutado.getProcesoNombre());
        
        TipoProceso tipo = pEjecutado.getTipo();
        String mensaje = "CPU_BOUND";
        if (tipo == TipoProceso.IO_BOUND){
            mensaje = "IO_BOUND";
        }
        tipoProceso.setText(mensaje);
                
    }
    
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelRelojGlobal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tipoProceso = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        idProceso = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nombreProceso = new javax.swing.JLabel();
        jScrollPaneListo = new javax.swing.JScrollPane();
        jScrollPaneBloqueado = new javax.swing.JScrollPane();
        jLabel7 = new javax.swing.JLabel();
        jScrollPaneCompletado = new javax.swing.JScrollPane();
        jLabel9 = new javax.swing.JLabel();
        jScrollPaneListoSuspendido = new javax.swing.JScrollPane();
        jScrollPaneListoBloqueado = new javax.swing.JScrollPane();
        jLabel10 = new javax.swing.JLabel();
        jSliderCiclo = new javax.swing.JSlider();
        jLabel = new javax.swing.JLabel();
        jLabelCiclo = new javax.swing.JLabel();
        jScrollPaneNuevo = new javax.swing.JScrollPane();
        jLabel12 = new javax.swing.JLabel();
        jButtonCambiarCiclo = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuCrearProceso = new javax.swing.JMenu();
        jMenuItemCrearProceso = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Bloqueado");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 130, 30));

        jLabelRelojGlobal.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabelRelojGlobal.setForeground(new java.awt.Color(0, 0, 0));
        jLabelRelojGlobal.setText("0 seg");
        jPanel1.add(jLabelRelojGlobal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 170, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 255));
        jLabel4.setText("Ejecutando");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 130, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 255, 0));
        jLabel5.setText("Nuevo");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 120, 30));

        jPanel2.setBackground(new java.awt.Color(221, 211, 231));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 4, true));
        jPanel2.setForeground(new java.awt.Color(204, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Tipo:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 30, 20));

        tipoProceso.setForeground(new java.awt.Color(0, 0, 0));
        tipoProceso.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tipoProceso.setText("-----");
        jPanel2.add(tipoProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 80, 20));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("ID:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 30, 20));

        idProceso.setForeground(new java.awt.Color(0, 0, 0));
        idProceso.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        idProceso.setText("0000");
        jPanel2.add(idProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 80, 20));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Nombre:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 60, 20));

        nombreProceso.setForeground(new java.awt.Color(0, 0, 0));
        nombreProceso.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nombreProceso.setText("vacio");
        jPanel2.add(nombreProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 80, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 180, 150));
        jPanel1.add(jScrollPaneListo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 840, 80));
        jPanel1.add(jScrollPaneBloqueado, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 840, 80));

        jLabel7.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Completado");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 150, 30));
        jPanel1.add(jScrollPaneCompletado, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 840, 80));

        jLabel9.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 0));
        jLabel9.setText("Listo Bloqueado");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 560, 200, 30));
        jPanel1.add(jScrollPaneListoSuspendido, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 600, 410, 80));
        jPanel1.add(jScrollPaneListoBloqueado, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 600, 410, 80));

        jLabel10.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 0));
        jLabel10.setText("Listo Suspendido");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 560, 200, 30));

        jSliderCiclo.setBackground(new java.awt.Color(204, 153, 255));
        jSliderCiclo.setForeground(new java.awt.Color(102, 102, 102));
        jSliderCiclo.setMaximum(1000);
        jSliderCiclo.setMinimum(500);
        jPanel1.add(jSliderCiclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, -1, 30));

        jLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel.setForeground(new java.awt.Color(0, 0, 0));
        jLabel.setText("Valor ciclo:");
        jPanel1.add(jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, -1, -1));

        jLabelCiclo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelCiclo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCiclo.setText("500 ms");
        jPanel1.add(jLabelCiclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, -1, -1));
        jPanel1.add(jScrollPaneNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 840, 80));

        jLabel12.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 153, 0));
        jLabel12.setText("Listo");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 70, 30));

        jButtonCambiarCiclo.setText("cambiar");
        jPanel1.add(jButtonCambiarCiclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, 100, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Reloj:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 70, 30));

        jMenu2.setText("Politicas de planificacion");

        jMenuItem1.setText("FCFS");
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Round Robin");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("SPN");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("SRT");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("HRRN");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("FeedBack");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenuCrearProceso.setText("Crear proceso");

        jMenuItemCrearProceso.setText("Crear proceso");
        jMenuCrearProceso.add(jMenuItemCrearProceso);

        jMenuBar1.add(jMenuCrearProceso);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1287, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel *///<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel idProceso;
    private javax.swing.JButton jButtonCambiarCiclo;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCiclo;
    private javax.swing.JLabel jLabelRelojGlobal;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCrearProceso;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItemCrearProceso;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPaneBloqueado;
    private javax.swing.JScrollPane jScrollPaneCompletado;
    private javax.swing.JScrollPane jScrollPaneListo;
    private javax.swing.JScrollPane jScrollPaneListoBloqueado;
    private javax.swing.JScrollPane jScrollPaneListoSuspendido;
    private javax.swing.JScrollPane jScrollPaneNuevo;
    private javax.swing.JSlider jSliderCiclo;
    private javax.swing.JLabel nombreProceso;
    private javax.swing.JLabel tipoProceso;
    // End of variables declaration//GEN-END:variables
}
