/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Modelado_de_procesos.PCB;
import Modelado_de_procesos.TipoProceso;
import Politicas_de_Planificacion.HRRN;
import Politicas_de_Planificacion.SPN;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.JOptionPane;
import main.CPU;

/**
 *
 * @author pjroj
 */
public class VentanaPoliticas extends javax.swing.JFrame {

    /**
     * Creates new form CrearProceso
     */
    public VentanaPoliticas() {
        initComponents();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        SPN = new javax.swing.JButton();
        FCFS = new javax.swing.JButton();
        SRT = new javax.swing.JButton();
        ROUND_ROBIN = new javax.swing.JButton();
        FEEDBACK = new javax.swing.JButton();
        HRRN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("POLITICAS PLANIFICACION");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 190, 20));

        SPN.setText("SPN");
        SPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPNActionPerformed(evt);
            }
        });
        jPanel1.add(SPN, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 120, 30));

        FCFS.setText("FCFS");
        FCFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FCFSActionPerformed(evt);
            }
        });
        jPanel1.add(FCFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 120, 30));

        SRT.setText("SRT");
        SRT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SRTActionPerformed(evt);
            }
        });
        jPanel1.add(SRT, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 120, 30));

        ROUND_ROBIN.setText("ROUND ROBIN");
        ROUND_ROBIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ROUND_ROBINActionPerformed(evt);
            }
        });
        jPanel1.add(ROUND_ROBIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 120, 30));

        FEEDBACK.setText("FEEDBACK");
        FEEDBACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FEEDBACKActionPerformed(evt);
            }
        });
        jPanel1.add(FEEDBACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 120, 30));

        HRRN.setText("HRRN");
        HRRN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HRRNActionPerformed(evt);
            }
        });
        jPanel1.add(HRRN, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 120, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPNActionPerformed
        CPU.setSPN(true);
        SPN spn = new SPN();
        spn.organizarCola(CPU.getColaNuevos());
        Ventana2 ventana2 = new Ventana2();
        ventana2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SPNActionPerformed

    private void FCFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FCFSActionPerformed
        CPU.setFCFS(true);
        Ventana2 ventana2 = new Ventana2();
        ventana2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_FCFSActionPerformed

    private void SRTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SRTActionPerformed
        CPU.setSRT(true);
        Ventana2 ventana2 = new Ventana2();
        ventana2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SRTActionPerformed

    private void ROUND_ROBINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ROUND_ROBINActionPerformed
        CPU.setROUND_ROBIN(true);
        Ventana2 ventana2 = new Ventana2();
        ventana2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ROUND_ROBINActionPerformed

    private void FEEDBACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FEEDBACKActionPerformed
        CPU.setFEEDBACK(true);
        Ventana2 ventana2 = new Ventana2();
        ventana2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_FEEDBACKActionPerformed

    private void HRRNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HRRNActionPerformed
        CPU.setHRRN(true);
        HRRN hrrn = new HRRN();
        hrrn.organizarCola(CPU.getColaNuevos());
        CPU.getColaListos().print2();
        Ventana2 ventana2 = new Ventana2();
        ventana2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HRRNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPoliticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPoliticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPoliticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPoliticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPoliticas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FCFS;
    private javax.swing.JButton FEEDBACK;
    private javax.swing.JButton HRRN;
    private javax.swing.JButton ROUND_ROBIN;
    private javax.swing.JButton SPN;
    private javax.swing.JButton SRT;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
